# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collaborative-editor.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'collaborative-editor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ollaborative-editor.proto\x12\x13\x63ollaborativeeditor\"\x0f\n\rDocumentQuery\"\xb5\x01\n\x0b\x45\x64itRequest\x12\x37\n\x04type\x18\x01 \x01(\x0e\x32).collaborativeeditor.EditRequest.EditType\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0c\n\x04span\x18\x04 \x01(\x05\x12\x11\n\teditor_id\x18\x05 \x01(\t\".\n\x08\x45\x64itType\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06MODIFY\x10\x01\x12\n\n\x06REMOVE\x10\x02\"Z\n\rDocumentState\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\thas_error\x18\x02 \x01(\x08\x12\x15\n\rerror_details\x18\x03 \x01(\t\x12\x11\n\teditor_id\x18\x04 \x01(\t\"P\n\nEditRecord\x12\x11\n\tedit_type\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\x11\n\teditor_id\x18\x04 \x01(\t\"!\n\rAuditResponse\x12\x10\n\x08recorded\x18\x01 \x01(\x08\x32\xae\x02\n\x0f\x44ocumentService\x12\\\n\x0eModifyDocument\x12 .collaborativeeditor.EditRequest\x1a\".collaborativeeditor.DocumentState\"\x00(\x01\x30\x01\x12Y\n\rFetchDocument\x12\".collaborativeeditor.DocumentQuery\x1a\".collaborativeeditor.DocumentState\"\x00\x12\x62\n\x14WatchDocumentChanges\x12\".collaborativeeditor.DocumentQuery\x1a\".collaborativeeditor.DocumentState\"\x00\x30\x01\x32\x63\n\x0c\x41uditService\x12S\n\nRecordEdit\x12\x1f.collaborativeeditor.EditRecord\x1a\".collaborativeeditor.AuditResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collaborative_editor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENTQUERY']._serialized_start=51
  _globals['_DOCUMENTQUERY']._serialized_end=66
  _globals['_EDITREQUEST']._serialized_start=69
  _globals['_EDITREQUEST']._serialized_end=250
  _globals['_EDITREQUEST_EDITTYPE']._serialized_start=204
  _globals['_EDITREQUEST_EDITTYPE']._serialized_end=250
  _globals['_DOCUMENTSTATE']._serialized_start=252
  _globals['_DOCUMENTSTATE']._serialized_end=342
  _globals['_EDITRECORD']._serialized_start=344
  _globals['_EDITRECORD']._serialized_end=424
  _globals['_AUDITRESPONSE']._serialized_start=426
  _globals['_AUDITRESPONSE']._serialized_end=459
  _globals['_DOCUMENTSERVICE']._serialized_start=462
  _globals['_DOCUMENTSERVICE']._serialized_end=764
  _globals['_AUDITSERVICE']._serialized_start=766
  _globals['_AUDITSERVICE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
